name: Deploy to Deta
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #Be sure you check-out the repo first. Deta CLI needs access to the files
      - uses: BogDAAAMN/deta-deploy-action@v1.0.0
        with:
          deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }} #Deta access token https://docs.deta.sh/docs/cli/auth
          deta-name: 'Polmo-FastAPI-backend' #Deta Micro name https://docs.deta.sh/docs/cli/commands/#deta-clone
          deta-project: 'Polimo' #Deta project name https://docs.deta.sh/docs/cli/commands/#deta-clone
